#pragma once

#include <cstddef>

#define BIT(n) (1 << n)

namespace MiMa {
	enum StatusBit : uint32_t {
		FOLLOWING_ADDRESS = 0xFF,
		RESERVED = 0x300,
		STORAGE_WRITING = BIT(10),
		STORAGE_READING = BIT(11),
		ALU_C = 0x7000,
		SAR_READING = BIT(15),
		SDR_WRITING = BIT(16),
		SDR_READING = BIT(17),
		IR_WRITING = BIT(18),
		IR_READING = BIT(19),
		IAR_WRITING = BIT(20),
		IAR_READING = BIT(21),
		ONE = BIT(22),
		ALU_RESULT = BIT(23),
		ALU_RIGHT_OPERAND = BIT(24),
		ALU_LEFT_OPERAND = BIT(25),
		ACCUMULATOR_WRITING = BIT(26),
		ACCUMULATOR_READING = BIT(27),
		UNDEFINED = 0xF0000000
	};
}
